#nullable enable
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ConsoleForge.SourceGen;

/// <summary>
/// Roslyn incremental source generator that handles the <c>[Component]</c>
/// attribute. Emits <c>Init()</c> and the explicit
/// <c>IComponent&lt;TResult&gt;.Result</c> property when the type
/// implements <c>IComponent&lt;TResult&gt;</c> and hasn't declared them manually.
/// </summary>
[Generator]
public sealed class ComponentGenerator : IIncrementalGenerator
{
    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targets = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "ConsoleForge.Core.ComponentAttribute",
                predicate: static (node, _) => node is TypeDeclarationSyntax,
                transform: static (ctx, ct) => GetTarget(ctx, ct))
            .Where(static t => t is not null && t.HasWork);

        context.RegisterSourceOutput(targets,
            static (spc, target) => Emit(spc, target!));
    }

    private static GenerationTarget? GetTarget(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol)
            return null;

        ct.ThrowIfCancellationRequested();

        // Skip if it ALSO has DispatchUpdateAttribute, because DispatchUpdateGenerator handles the combo
        if (typeSymbol.GetAttributes().Any(a => a.AttributeClass?.Name == "DispatchUpdateAttribute"))
            return null;

        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : typeSymbol.ContainingNamespace.ToDisplayString();

        var typeName = typeSymbol.Name;
        var typeKind = typeSymbol.IsRecord ? "record" : "class";

        var icomp = typeSymbol.AllInterfaces
            .FirstOrDefault(i => i.Name == "IComponent" && i.TypeArguments.Length == 1);

        string? resultTypeName = null;
        bool emitResultProperty = false;
        bool emitInit = false;

        if (icomp != null)
        {
            resultTypeName = icomp.TypeArguments[0]
                .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            emitResultProperty = !typeSymbol.GetMembers("Result")
                .OfType<IPropertySymbol>()
                .Any(p => !p.IsImplicitlyDeclared && p.ExplicitInterfaceImplementations.Length > 0);

            emitInit = !typeSymbol.GetMembers("Init")
                .OfType<IMethodSymbol>()
                .Any(m => !m.IsImplicitlyDeclared);
        }

        bool hasWork = emitResultProperty || emitInit;
        
        return new GenerationTarget(ns, typeName, typeKind, emitInit, emitResultProperty, resultTypeName, hasWork);
    }

    private static void Emit(SourceProductionContext spc, GenerationTarget target)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Source: ConsoleForge.SourceGen — ComponentGenerator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(target.Namespace))
        {
            sb.AppendLine($"namespace {target.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial {target.TypeKind} {target.TypeName}");
        sb.AppendLine("{");

        if (target.EmitResultProperty && target.ResultTypeName != null)
        {
            sb.AppendLine($"    {target.ResultTypeName} "
                + $"global::ConsoleForge.Core.IComponent<{target.ResultTypeName}>.Result"
                + " => Result!;");
            sb.AppendLine();
        }

        if (target.EmitInit)
        {
            sb.AppendLine("    public global::ConsoleForge.Core.ICmd? Init() => null;");
            sb.AppendLine();
        }

        sb.AppendLine("}");

        spc.AddSource(
            $"{target.TypeName}.component.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record GenerationTarget(
        string Namespace,
        string TypeName,
        string TypeKind,
        bool EmitInit,
        bool EmitResultProperty,
        string? ResultTypeName,
        bool HasWork);
}