#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using ConsoleForge.SourceGen;

/// <summary>
/// Roslyn incremental source generator that handles the <c>[DispatchUpdate]</c>
/// attribute. Scans the target type for <c>On{MsgType}()</c> handler methods and
/// emits the <c>Update(IMsg)</c> switch dispatch. Optionally emits
/// <c>[Component]</c> scaffolding when both attributes are present.
/// </summary>
[Generator]
public sealed class DispatchUpdateGenerator : IIncrementalGenerator
{
    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targets = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                    "ConsoleForge.Core.DispatchUpdateAttribute",
                    predicate: static (node, _) => true,
                    transform: static (ctx, ct) => GetTarget(ctx, ct))
            .Where(static t => t is not null);

        context.RegisterSourceOutput(targets,
                static (spc, target) => 
                {
                    if (target!.Diagnostic != null)
                    {
                        // Fatal / skip diagnostics (CFG001, CFG004) — report and do not emit
                        spc.ReportDiagnostic(target.Diagnostic);
                        return;
                    }

                    // Per-handler warnings (CFG002, CFG003) — report but still emit
                    foreach (var d in target.HandlerDiagnostics)
                        spc.ReportDiagnostic(d);

                    Emit(spc, target);
                });
    }

    private static void Emit(SourceProductionContext spc, GenerationTarget target)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Source: ConsoleForge.SourceGen — DispatchUpdateGenerator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(target.Namespace))
        {
            sb.AppendLine($"namespace {target.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial {target.TypeKind} {target.TypeName}");
        sb.AppendLine("{");

        // ── [Component] scaffolding ──────────────────────────────────────────
        if (target.EmitResultProperty && target.ResultTypeName != null)
        {
            sb.AppendLine($"    {target.ResultTypeName} "
                + $"global::ConsoleForge.Core.IComponent<{target.ResultTypeName}>.Result"
                + " => Result!;");
            sb.AppendLine();
        }

        if (target.EmitInit)
        {
            sb.AppendLine("    public global::ConsoleForge.Core.ICmd? Init() => null;");
            sb.AppendLine();
        }

        // ── Update dispatch ──────────────────────────────────────────────────
        sb.AppendLine("    public ("
            + "global::ConsoleForge.Core.IModel Model, "
            + "global::ConsoleForge.Core.ICmd? Cmd)");
        sb.AppendLine("        Update(global::ConsoleForge.Core.IMsg msg)");
        sb.AppendLine("    {");

        if (target.HasKeyMap)
            sb.AppendLine("        if (Keys.Handle(msg) is { } action) msg = action;");

        sb.AppendLine("        return msg switch");
        sb.AppendLine("        {");

        foreach (var h in target.Handlers)
        {
            if (h.TakesMsg)
                // Cast required: switch arm binds as IMsg, handler expects concrete type
                sb.AppendLine($"            {h.MsgTypeName} __m => {h.MethodName}(({h.MsgTypeName})__m),");
            else
                sb.AppendLine($"            {h.MsgTypeName} => {h.MethodName}(),");
        }

        sb.AppendLine("            _ => (this, null),");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource(
            $"{target.TypeName}.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static GenerationTarget? GetTarget(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol)
            return null;

        ct.ThrowIfCancellationRequested();

        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : typeSymbol.ContainingNamespace.ToDisplayString();

        var typeName = typeSymbol.Name;
        var typeKind = typeSymbol.IsRecord ? "record" : "class";

        // CFG001: must be partial to receive generated code
        var isPartial = typeSymbol.DeclaringSyntaxReferences
            .Select(r => r.GetSyntax())
            .OfType<TypeDeclarationSyntax>()
            .Any(n => n.Modifiers.Any(SyntaxKind.PartialKeyword));

        if (!isPartial)
            return new GenerationTarget(ns, typeName, typeKind, false,
                EquatableArray<HandlerInfo>.Empty, false, false, null,
                Diagnostic.Create(ConsoleForge.SourceGen.Diagnostics.MissingPartial,
                    typeSymbol.Locations.FirstOrDefault(), typeName));

        // CFG004: user already hand-wrote Update() — skip generation, emit info
        bool hasExistingUpdate = typeSymbol
            .GetMembers("Update")
            .OfType<IMethodSymbol>()
            .Any(m => !m.IsImplicitlyDeclared);

        if (hasExistingUpdate)
            return new GenerationTarget(ns, typeName, typeKind, false,
                EquatableArray<HandlerInfo>.Empty, false, false, null,
                Diagnostic.Create(ConsoleForge.SourceGen.Diagnostics.HasExistingUpdate,
                    typeSymbol.Locations.FirstOrDefault(), typeName));

        // KeyMap detection
        bool hasKeyMap = typeSymbol.GetMembers("Keys").Any(m =>
                m is IFieldSymbol { IsStatic: true } f && f.Type.Name == "KeyMap" ||
                m is IPropertySymbol { IsStatic: true } p && p.Type.Name == "KeyMap");

        // [Component] / IComponent<T> handling
        bool hasComponentAttr = typeSymbol.GetAttributes()
            .Any(a => a.AttributeClass?.Name == "ComponentAttribute");

        string? resultTypeName = null;
        bool emitResultProperty = false;
        bool emitInit = false;

        if (hasComponentAttr)
        {
            // Check for IComponent<T> (generic) — emits Result property + Init
            var icomp = typeSymbol.AllInterfaces
                .FirstOrDefault(i => i.Name == "IComponent" && i.TypeArguments.Length == 1);

            if (icomp != null)
            {
                resultTypeName = icomp.TypeArguments[0]
                    .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                emitResultProperty = !typeSymbol.GetMembers("Result")
                    .OfType<IPropertySymbol>()
                    .Any(p => !p.IsImplicitlyDeclared
                            && p.ExplicitInterfaceImplementations.Length > 0);
            }

            // Emit Init() if the type implements IComponent (generic or non-generic) and hasn't written it
            bool implementsAnyIComponent = typeSymbol.AllInterfaces
                .Any(i => i.Name == "IComponent");

            if (implementsAnyIComponent)
            {
                emitInit = !typeSymbol.GetMembers("Init")
                    .OfType<IMethodSymbol>()
                    .Any(m => !m.IsImplicitlyDeclared);
            }
        }

        // Handler discovery
        var handlers     = new List<HandlerInfo>();
        var handlerDiags = new List<Diagnostic>();
        var seenMsgFqns  = new Dictionary<string, string>(StringComparer.Ordinal); // FQN → first method name

        foreach (var method in typeSymbol.GetMembers().OfType<IMethodSymbol>())
        {
            ct.ThrowIfCancellationRequested();

            // Name must be On{UpperLetter}...
            if (method.Name.Length < 3
                    || !method.Name.StartsWith("On")
                    || !char.IsUpper(method.Name[2]))
                continue;

            if (!IsValidHandlerReturnType(method.ReturnType))
            {
                handlerDiags.Add(Diagnostic.Create(
                    ConsoleForge.SourceGen.Diagnostics.HandlerReturnTypeMismatch,
                    method.Locations.FirstOrDefault(),
                    method.Name));
                continue;
            }

            // Infer message type: OnNavUp -> NavUpMsg
            var inferredName = method.Name.Substring(2) + "Msg";
            var msgType = ctx.SemanticModel.Compilation
                .GetSymbolsWithName(inferredName, SymbolFilter.Type)
                .OfType<INamedTypeSymbol>()
                .FirstOrDefault();

            if (msgType == null)
            {
                handlerDiags.Add(Diagnostic.Create(
                    ConsoleForge.SourceGen.Diagnostics.MsgTypeNotFound,
                    method.Locations.FirstOrDefault(),
                    method.Name,
                    $"'{inferredName}' not found in scope"));
                continue;
            }

            var msgFqn = msgType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            if (seenMsgFqns.TryGetValue(msgFqn, out var firstMethodName))
            {
                handlerDiags.Add(Diagnostic.Create(
                    ConsoleForge.SourceGen.Diagnostics.MsgTypeNotFound,
                    method.Locations.FirstOrDefault(),
                    method.Name,
                    $"'{msgFqn}' already handled by '{firstMethodName}', first wins"));
                continue;
            }

            seenMsgFqns[msgFqn] = method.Name;

            // Does the method take the message as a parameter?
            bool takesMsg = method.Parameters.Length == 1
                && SymbolEqualityComparer.Default.Equals(method.Parameters[0].Type, msgType);

            handlers.Add(new HandlerInfo(method.Name, msgFqn, takesMsg));
        }

        return new GenerationTarget(
                ns, typeName, typeKind, hasKeyMap,
                new EquatableArray<HandlerInfo>(handlers),
                emitInit, emitResultProperty, resultTypeName,
                HandlerDiagnostics: new EquatableArray<Diagnostic>(handlerDiags));
    }

    // Return type validity: must be a 2-element tuple whose first element is IModel
    // and second is ICmd? (nullable annotation required)
    private static bool IsValidHandlerReturnType(ITypeSymbol returnType)
    {
        if (returnType is not INamedTypeSymbol { IsTupleType: true } tuple)
            return false;
        if (tuple.TupleElements.Length != 2)
            return false;

        var first = tuple.TupleElements[0].Type;
        var second = tuple.TupleElements[1].Type;

        return first.Name == "IModel"
            && second.Name == "ICmd"
            && second.NullableAnnotation == NullableAnnotation.Annotated;
    }

    private sealed record GenerationTarget(
        string Namespace,
        string TypeName,
        string TypeKind,                   // "record" or "class"
        bool HasKeyMap,                    // true if a static field/property named 'Keys' of type KeyMap exists
        EquatableArray<HandlerInfo> Handlers,
        bool EmitInit,                     // from [Component] — only if user hasn't written Init() already
        bool EmitResultProperty,           // from [Component] — only if user hasn't written explicit Result already
        string? ResultTypeName,            // fully-qualified, e.g. "global::System.String"
        Diagnostic? Diagnostic = null,     // fatal/skip diagnostic (CFG001, CFG004) — blocks emit when set
        EquatableArray<Diagnostic> HandlerDiagnostics = default); // per-handler warnings (CFG002, CFG003)

    private sealed record HandlerInfo(
        string MethodName,             // e.g. "OnNavUp"
        string MsgTypeName,            // fully-qualified, e.g. "global::My.App.NavUpMsg"
        bool TakesMsg);              // true if method declares a (XMsg msg) parameter
}

// Polyfill: 'record' init-only setters require this type, absent in netstandard2.0
#pragma warning disable IDE0130 // Namespace does not match folder structure
namespace System.Runtime.CompilerServices
#pragma warning restore IDE0130 // Namespace does not match folder structure
{
    /// <summary>Polyfill for init-only setter support on netstandard2.0.</summary>
    internal static class IsExternalInit { }
}